# fly.toml app configuration file generated for guia-da-sorte on 2024-09-04T23:57:21-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'guia-da-sorte'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = "requests"
    soft_limit = 20
    hard_limit = 25

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
